name: enterprise_mcp_agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - "mcp<2"
      - pydantic
      - python-dotenv
      - langchain>=0.3.0
      - langchain-community>=0.3.0
      - langchain-ollama>=0.2.0
      - langchain-aws
      - langchain-google-vertexai
      - langchain-openai
      - azure-identity
      - langgraph>=0.2.0
      - fastapi
      - uvicorn
      - numpy
      - requests
      - rich
